# Generated by Django 5.1.2 on 2024-10-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner_course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnercourse',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_covers/'),
        ),
    ]
