# Generated by Django 5.1.2 on 2024-10-29 09:30

import learner_course.path_provider
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner_course', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecontent',
            name='image_file',
            field=models.ImageField(upload_to=learner_course.path_provider.user_directory_path),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='video_file',
            field=models.FileField(upload_to=learner_course.path_provider.user_directory_path),
        ),
    ]
